import type { Policy, Scenario, Experiment } from './types';
export const SCENARIOS: Scenario[] = [
  {
    id: 'checkout',
    name: 'Checkout payments',
    eyebrow: 'Duplicate writes',
    icon: 'credit',
    description:
      'A four-step checkout with rate limits, timeouts, and malformed receipts. Payment timeouts happen after the charge commits.',
    steps: [
      {
        id: 'search',
        name: 'catalog.search',
        kind: 'read',
        latencyMs: 180,
        costMicros: 120,
        fault: 'rate_limit',
        supportsIdempotency: false,
      },
      {
        id: 'inventory',
        name: 'inventory.check',
        kind: 'read',
        latencyMs: 240,
        costMicros: 80,
        fault: 'timeout_before',
        supportsIdempotency: false,
      },
      {
        id: 'payment',
        name: 'payments.charge',
        kind: 'write',
        latencyMs: 320,
        costMicros: 300,
        fault: 'timeout_after_write',
        supportsIdempotency: true,
      },
      {
        id: 'receipt',
        name: 'receipt.render',
        kind: 'read',
        latencyMs: 160,
        costMicros: 100,
        fault: 'malformed',
        supportsIdempotency: false,
      },
    ],
  },
  {
    id: 'research',
    name: 'Research pipeline',
    eyebrow: 'Malformed responses',
    icon: 'search',
    description:
      'A four-step research workflow with rate-limited search, fetch timeouts, and malformed extraction output.',
    steps: [
      {
        id: 'search',
        name: 'web.search',
        kind: 'read',
        latencyMs: 250,
        costMicros: 800,
        fault: 'rate_limit',
        supportsIdempotency: false,
      },
      {
        id: 'fetch',
        name: 'page.fetch',
        kind: 'read',
        latencyMs: 600,
        costMicros: 100,
        fault: 'timeout_before',
        supportsIdempotency: false,
      },
      {
        id: 'extract',
        name: 'facts.extract',
        kind: 'read',
        latencyMs: 400,
        costMicros: 600,
        fault: 'malformed',
        supportsIdempotency: false,
      },
      {
        id: 'check',
        name: 'citations.verify',
        kind: 'read',
        latencyMs: 150,
        costMicros: 200,
        fault: 'none',
        supportsIdempotency: false,
      },
    ],
  },
  {
    id: 'devops',
    name: 'Incident response',
    eyebrow: 'Permanent errors',
    icon: 'terminal',
    description:
      'An incident workflow with a possible authorization failure and a notification tool that cannot deduplicate repeated writes.',
    steps: [
      {
        id: 'logs',
        name: 'logs.query',
        kind: 'read',
        latencyMs: 220,
        costMicros: 300,
        fault: 'rate_limit',
        supportsIdempotency: false,
      },
      {
        id: 'metrics',
        name: 'metrics.fetch',
        kind: 'read',
        latencyMs: 180,
        costMicros: 200,
        fault: 'timeout_before',
        supportsIdempotency: false,
      },
      {
        id: 'deploy',
        name: 'deploy.inspect',
        kind: 'read',
        latencyMs: 300,
        costMicros: 100,
        fault: 'permanent',
        supportsIdempotency: false,
      },
      {
        id: 'notify',
        name: 'incident.post',
        kind: 'write',
        latencyMs: 200,
        costMicros: 100,
        fault: 'timeout_after_write',
        supportsIdempotency: false,
      },
    ],
  },
];
export const BASELINE: Policy = {
  id: 'baseline',
  name: 'Blind retry',
  maxAttempts: 3,
  backoffMs: 100,
  timeoutMs: 1500,
  budgetMs: 15000,
  validateOutput: false,
  honorRetryAfter: false,
  useIdempotency: false,
  retryPermanent: true,
  retryAmbiguous: true,
};
export const GUARDED: Policy = {
  id: 'candidate',
  name: 'Guarded retry',
  maxAttempts: 3,
  backoffMs: 600,
  timeoutMs: 1500,
  budgetMs: 15000,
  validateOutput: true,
  honorRetryAfter: true,
  useIdempotency: true,
  retryPermanent: false,
  retryAmbiguous: false,
};
export const DEFAULT_EXPERIMENT: Experiment = {
  version: 1,
  scenarioId: 'checkout',
  seed: 1720,
  trials: 250,
  faultRate: 0.35,
  candidate: { ...GUARDED },
};
export function getScenario(id: string): Scenario {
  const s = SCENARIOS.find((x) => x.id === id);
  if (!s) throw new Error('Unknown scenario');
  return s;
}
